#!/usr/bin/env zsh

# Execute Programs On VSCode Termial Startup
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  if [[ "${DEVBOX_WD}" == "" ]]; then
    exec devbox shell
  fi
fi


if [ -e /home/devbox/.nix-profile/etc/profile.d/nix.sh ]; then . /home/devbox/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
