repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        name: Check YAML
        description: Validate YAML files.
      - id: check-json
        name: Check JSON
        description: Validate JSON files.
      - id: trailing-whitespace
        name: Trailing Whitespace
        description: Remove trailing whitespace in files.
      - id: end-of-file-fixer
        name: End of File Fixer
        description: Ensure files end with a newline.

  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.3.0
    hooks:
      - id: editorconfig-checker
        name: EditorConfig Checker
        description: Check files against EditorConfig rules.
